name: Flow Ambiente UAT

on:
  workflow_call:

jobs:

  analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: CodeFlowTech/sre/modules/analysis/sonarqube@main

  security:
    needs: analysis
    runs-on: ubuntu-latest
    steps:
      - name: Security check
        shell: bash
        run: echo "Running security checks"

  build:
    needs: [analysis, security]
    runs-on: ubuntu-latest
    steps:
      - uses: CodeFlowTech/sre/modules/build/dotnet@main

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: CodeFlowTech/sre/modules/deploy/argocd@main

  test:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Test
        shell: bash
        run: echo "Running tests"

  notification:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: CodeFlowTech/sre/modules/notifications/elastic-search@main
