name: Pipeline

on:
  workflow_call:

jobs:

  validator:
    runs-on: ubuntu-latest
    steps:      
      - uses: CodeFlowTech/sre/modules/build/dotnet@main

  build:
    needs: validator
    runs-on: ubuntu-latest
    steps:
      - uses: CodeFlowTech/sre/modules/build/dotnet@main

  # test:
  #   needs: build
  #   uses: CodeFlowTech/sre/.github/workflows/test.yml@main

  # analysis:
  #   needs: test
  #   uses: CodeFlowTech/sre/.github/workflows/analysis.yml@main

  # deploy:
  #   needs: analysis
  #   uses: CodeFlowTech/sre/.github/workflows/deploy.yml@main

  # notification:
  #   needs: deploy
  #   uses: CodeFlowTech/sre/.github/workflows/notification.yml@main