name: Pipeline

on:
  workflow_call:

jobs:

  validator:
    runs-on: ubuntu-latest
    outputs:
      ambiente: ${{ steps.validation.outputs.ambiente }}
    steps:
      - id: validation
        uses: CodeFlowTech/sre/modules/validators/validation@main
  
  test_analyse:
    runs-on: ubuntu-latest
    steps:
      - id: test_analyse
        uses: CodeFlowTech/sre/modules/validators/validation@main

  build:
    runs-on: ubuntu-latest
    steps:
      - id: build
        uses: CodeFlowTech/sre/modules/validators/validation@main

  approval:
    runs-on: ubuntu-latest
    steps:
      - id: approval
        uses: CodeFlowTech/sre/modules/validators/validation@main

  deploy:
    runs-on: ubuntu-latest
    steps:
      - id: deploy
        uses: CodeFlowTech/sre/modules/validators/validation@main

  comunicate:
    runs-on: ubuntu-latest
    steps:
      - id: comunicate
        uses: CodeFlowTech/sre/modules/validators/validation@main

