name: Pipeline

on:
  workflow_call:

jobs:

  validator:
    runs-on: ubuntu-latest
    steps:      
      - uses: CodeFlowTech/sre/modules/build/dotnet@main
  
  flow:
    uses: CodeFlowTech/sre/modules/validators/validation@main

