name: Pipeline

on:
  workflow_call:

jobs:

  validator:
    runs-on: ubuntu-latest
    outputs:
      ambiente: ${{ steps.validation.outputs.ambiente }}
    steps:
      - id: validation
        uses: CodeFlowTech/sre/modules/validators/validation@main
  
  hml:
    needs: validator
    if: needs.validator.outputs.ambiente == 'hml'
    uses: CodeFlowTech/sre/.github/workflows/flow-ambiente-hml.yml@main

  prd:
    needs: validator
    if: needs.validator.outputs.ambiente == 'prd'
    uses: CodeFlowTech/sre/.github/workflows/flow-ambiente-prd.yml@main

  uat:
    needs: validator
    if: needs.validator.outputs.ambiente == 'uat'
    uses: CodeFlowTech/sre/.github/workflows/flow-ambiente-uat.yml@main

  pr:
    needs: validator
    if: needs.validator.outputs.ambiente == 'pullrequest'
    uses: CodeFlowTech/sre/.github/workflows/flow-pullrequest.yml@main
